- name: Setup Infrastructure
  hosts: localhost
  connection: local
  roles:
    # Пример использования своей роли
    # Структура директорий роли описана здесь https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
    - name: infrastructure
      vars:
        terraform_dir: "{{ playbook_dir }}/../terraform"
