# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3"

services:
  app: # Имя сервиса
    image: hexlet/hexlet-app
    container_name: hexlet-app
    restart: always
    env_file: .env # Файл, который содержит переменные окружения
    ports: # Проброс портов
    - 80:3000
    # Присваиваем переменные
    environment:
      - SERVER_MESSAGE=$HEXLET_SERVER_MESSAGE
      - ROLLBAR_TOKEN=$HEXLET_ROLLBAR_TOKEN
